org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# 避免 Windows 下 Kotlin 增量缓存跨盘符异常
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process

# 降低 Gradle 守护进程导致的缓存锁问题
org.gradle.daemon=false
org.gradle.parallel=false
